### ISSUE TITLE
Proof of Concept

### ISSUE THREAD

**Issue by KingLuvely** [SCCapstone/Seating-App#23]
- [x] Publish it on the Internet.
- [x] Create a github release.
- [x] Name it "Proof of Concept" 
- [x] Put the URL of your deployed app in the description textbox for that release. Also, if I need a username/password to access your site make sure you write those down in the textbox, and attach any other files or binaries I might need to test your app (ex, things to upload).
- [x] The webapp must be accessible until the last day of Finals.

Our issues:

- [x] #20 draw objects on canvas
- [x] #19 Implement Canvas object
- [x] #16 Remove reservations
- [x] #15 Edit reservations
- [x] #13 Add reservations
- [x] #12 Display reservation details
- [x] #11 Add login functionality
- [x] #10 Deploy to web
